#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: 2.1
commands:
  bazel-install:
    steps:
      - run: |
          mkdir install
          cd install
          curl -OL https://raw.githubusercontent.com/lolski/build-tools/refactor/tools/bazelinstall/linux.sh
          bash ./linux.sh
          curl -OL https://raw.githubusercontent.com/lolski/build-tools/refactor/tools/bazelinstall/rbe.sh
          bash ./rbe.sh
          cd ..
          rm -rf install

  bazel-run-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tools/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - bazel-run-rbe:
          command: bazel build //...
      - run: bazel run @graknlabs_dependencies//unuseddeps:unused-deps -- list

  test-client:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - bazel-run-rbe:
          command: bazel test //client/test --test_output=errors

  deploy-maven-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - run: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //client:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //protocol:deploy-maven -- snapshot

  test-deployment-maven:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - run: sed -i -e "s/GRABL_TRACING_VERSION_MARKER/$(git rev-parse HEAD)/g" test/deployment/pom.xml
      - run: cat test/deployment/pom.xml
      - run: cd test/deployment && mvn test

  sync-dependencies-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//ci:sync-dependencies -- \
          --source grabl-tracing@$(git rev-parse HEAD) \
          --targets client-java:master simulation:master grakn:master grabl:development

  deploy-github:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - run: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//ci:release-notes -- grabl-tracing $(cat VERSION) ./RELEASE_TEMPLATE.md
      - run: |
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run --define version=$(cat VERSION) //:deploy-github -- $CIRCLE_SHA1

  release-approval:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - bazel-install
      - checkout
      - run: |
          export RELEASE_APPROVAL_USERNAME=$REPO_GITHUB_USERNAME
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//ci:release-approval

  deploy-maven-release:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - run: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //protocol:deploy-maven -- release
          bazel run --define version=$(cat VERSION) //client:deploy-maven -- release

  sync-dependencies-release:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/grabl-tracing
    steps:
      - bazel-install
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//ci:sync-dependencies -- \
          --source grabl-tracing@$(git rev-parse HEAD) \
          --targets client-java:master simulation:master grakn:master grabl:development

  release-cleanup:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: git push --delete https://$REPO_GITHUB_TOKEN@github.com/graknlabs/grabl-tracing $CIRCLE_BRANCH

workflows:
  grabl-tracing:
    jobs:
      - build:
          filters:
            branches:
              ignore: grabl-tracing-release-branch
      - test-client:
          filters:
            branches:
              ignore: grabl-tracing-release-branch
      - deploy-maven-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
            - test-client
      - test-deployment-maven:
          filters:
            branches:
              only: master
          requires:
            - deploy-maven-snapshot
      - sync-dependencies-snapshot:
          filters:
            branches:
              only: master
          requires:
            - test-deployment-maven
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - sync-dependencies-snapshot

  grabl-tracing-release:
    jobs:
      - deploy-github:
          filters:
            branches:
              only: grabl-tracing-release-branch
      - deploy-approval:
          type: approval
          filters:
            branches:
              only: grabl-tracing-release-branch
          requires:
            - deploy-github
      - deploy-maven-release:
          filters:
            branches:
              only: grabl-tracing-release-branch
          requires:
            - deploy-approval
      - sync-dependencies-release:
          filters:
            branches:
              only: grabl-tracing-release-branch
          requires:
            - deploy-maven-release
      - release-cleanup:
          filters:
            branches:
              only: grabl-tracing-release-branch
          requires:
            - sync-dependencies-release