#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]

build:
  quality:
    filter:
      owner: graknlabs
      branch: dependency-analysis
    dependency-analysis:
      machine: graknlabs-ubuntu-20.04-java11
      script: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      machine: graknlabs-ubuntu-20.04
      script: |
        bazel build --config=rbe //...
        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
        bazel test --config=rbe $(bazel query 'kind(checkstyle_test, //...)')
    build-dependency:
      machine: graknlabs-ubuntu-20.04
      script: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
    test-client:
      machine: graknlabs-ubuntu-20.04
      script: |
        bazel test --config=rbe //client/test --test_output=errors
    deploy-maven-snapshot:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      script: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //client:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //protocol:deploy-maven -- snapshot
      dependencies: [build, build-dependency, test-client]
    test-deployment-maven:
      filter:
        owner: graknlabs
        branch: master
      machine: graknlabs-ubuntu-20.04
      script: |
        sed -i -e "s/GRABL_TRACING_VERSION_MARKER/$(git rev-parse HEAD)/g" test/deployment/pom.xml
        cat test/deployment/pom.xml
        cd test/deployment && mvn test
      dependencies: [deploy-maven-snapshot]

release:
  filter:
    owner: graknlabs
    branch: master
  deployment:
    deploy-github:
      machine: graknlabs-ubuntu-20.04
      script: |
        pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- grabl-tracing $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-maven-release:
      machine: graknlabs-ubuntu-20.04
      dependencies: [deploy-github]
      script: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //protocol:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //client:deploy-maven -- release
